name: conway
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - ffmpeg=8.0.0=gpl_he3062b8_906
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - glslang=16.0.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.1.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - icu=75.1=he0c23c2_0
  - imath=3.2.2=h1608b31_0
  - jasper=4.2.8=h8ad263b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libclang13=21.1.4=default_ha2db4b5_0
  - libcurl=8.16.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libflac=1.4.3=h63175ca_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.86.1=hd9c3897_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblapacke=3.9.0=38_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmad=0.15.1b=hcfcfb64_1001
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py310h3c58159_607
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - librsvg=2.60.0=hd5e4115_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h550210a_0
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - mkl=2025.3.0=hac47afa_454
  - mpg123=1.32.9=h01009b0_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.12.0=qt6_py310he543868_607
  - openexr=3.4.2=hce16647_1
  - openh264=2.6.0=hb17fa0b_0
  - openjph=0.25.0=hf13a347_0
  - openssl=3.6.0=h725018a_0
  - pango=1.56.4=h03d888a_0
  - pcre2=10.46=h3402e2f_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - portmidi=2.0.7=hac47afa_0
  - psutil=7.1.3=py310h1637853_0
  - pugixml=1.15=h372dad0_0
  - py-opencv=4.12.0=qt6_py310h9217539_607
  - pygame=2.6.1=py310hea55160_0
  - python=3.10.19=hc20f281_2_cpython
  - python_abi=3.10=8_cp310
  - qt6-main=6.9.3=ha0de62e_1
  - rav1e=0.7.1=ha073cba_3
  - scipy=1.15.2=py310h15c175c_0
  - sdl2=2.32.56=h5112557_0
  - sdl2_image=2.8.2=h5ca362a_1
  - sdl2_mixer=2.6.3=he8f0768_1
  - sdl2_ttf=2.24.0=hb42d5a6_0
  - sdl3=3.2.26=h5112557_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=haa9a63f_0
  - snappy=1.2.2=h7fa0ca8_0
  - spirv-tools=2025.4=h49e36cd_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_0
  - tk=8.6.13=h2c6b04d_2
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - jax==0.6.2
      - jaxlib==0.6.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-osc==1.9.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - sounddevice==0.5.3
